import admin from "../config/firebase.js";
import { AppError } from "../utils/appError.js";
import  User  from "../models/User.js";
import {generateToken} from "./../utils/generateToken.js";
import type { GoogleAuthInput } from "../validators/googleAuth.validator.js";



const safeUser = (user: InstanceType<typeof User>) => ({
  id: user._id,
  alias: user.alias,
  email: user.email,
  empathyScore: user.empathyScore,
  role: user.role,
});
 
// ─── Google Sign In ───────────────────────────────────────────
export const googleSignIn = async ({ idToken }: GoogleAuthInput) => {
  // 1. Verify the Google ID token with Firebase Admin
  let decodedToken;
  try {
    decodedToken = await admin.auth().verifyIdToken(idToken);
  } catch {
    throw new AppError("Invalid Google token", 401);
  }
 
  const { email, uid } = decodedToken;
 
  if (!email) {
    throw new AppError("Google account has no email", 400);
  }
 
  // 2. Check if user already exists
  let user = await User.findOne({ email });
 
  if (user) {
    // Existing user — update googleId if not set (e.g. registered with email first)
    if (!user.googleId) {
      user.googleId = uid;
      await user.save();
    }
  } else {
    // New user — create account, alias auto-generated by model
    user = await User.create({ email, googleId: uid });
  }
 
  // 3. Return our own JWT (not the Google token)
  const token = generateToken(user._id.toString());
 
  return {
    token,
    user: safeUser(user),
    isNewUser: !user.googleId, // useful for frontend onboarding flow
  };
};
